USE DATABASE OUR_FIRST_DB;

USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID VARCHAR(50),
    AMOUNT INT,
    PROFIT INT,
    PROFITABLE_FLAG BOOLEAN
) COMMENT = 'This table contains sample orders';

-- COPY INTO ORDERS
-- FROM (SELECT $1:order_id, $1:amount, $1:profit, $1:profitable_flag
-- FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE)
-- FILE_FORMAT = (
--     TYPE = CSV
--     FIELD_DELIMITER = ','
--     SKIP_HEADER = 1
-- )
-- FILES = ('OrderDetails.csv');
COPY INTO ORDERS
FROM
    (
        SELECT
            s.$1,
            s.$2,
            s.$3,
            CASE
                WHEN s.$3 > 0 THEN TRUE
                ELSE FALSE
            END
        FROM
            @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE s
    ) 
    FILE_FORMAT = (
        TYPE = CSV 
        FIELD_DELIMITER = ',' 
        SKIP_HEADER = 1
    ) 
    FILES = ('OrderDetails.csv');

SELECT
    *
FROM
    ORDERS;

CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.CUSTOMERS_NEW (
    CUSTOMER_ID VARCHAR(50),
    NAME VARCHAR(50),
    EMAIL VARCHAR(50)
) COMMENT = 'This table contains sample customers';

COPY INTO EXERCISE_DB.PUBLIC.CUSTOMERS_NEW (CUSTOMER_ID, NAME, EMAIL)
FROM
    (
        SELECT
            c.$1,
            CONCAT(c.$2, ' ', c.$3),
            c.$4
        FROM
            @MANAGE_DB.EXTERNAL_STAGES.CUSTOMER_STAGE c
    ) 
    FILE_FORMAT = (
        TYPE = CSV 
        FIELD_DELIMITER = ';' 
        SKIP_HEADER = 1
    ) 
    FILES = ('customers2.csv', 'customers3.csv');

SELECT
    *
FROM
    EXERCISE_DB.PUBLIC.CUSTOMERS_NEW;

TRUNCATE TABLE EXERCISE_DB.PUBLIC.CUSTOMERS_NEW;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_ERROR_EX
URL = 'S3://bucketsnowflakes4';

LIST @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_ERROR_EX;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_ERROR_EX (
    ORDER_ID VARCHAR(50),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(50),
    SUB_CATEGORY VARCHAR(50)
) COMMENT = 'This table contains sample orders with error handling';

SELECT
    *
FROM
    OUR_FIRST_DB.PUBLIC.ORDERS_ERROR_EX;

COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_ERROR_EX (
    ORDER_ID,
    AMOUNT,
    PROFIT,
    QUANTITY,
    CATEGORY,
    SUB_CATEGORY
)
FROM
    (
        SELECT
            s.$1,
            s.$2,
            s.$3,
            s.$4,
            s.$5,
            s.$6
        FROM
            @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_ERROR_EX s
    ) 
    FILE_FORMAT = (
        TYPE = CSV 
        FIELD_DELIMITER = ',' 
        SKIP_HEADER = 1
    ) 
    FILES = (
        'OrderDetails_error.csv',
        'OrderDetails_error2.csv'
    )
    -- ON_ERROR = 'ABORT_STATEMENT'; -- DEFAULT
    -- ON_ERROR = 'CONTINUE'; -- Continues loading even if there are errors
    -- ON_ERROR = 'SKIP_FILE'; -- Skips the entire file if any error occurs
    -- ON_ERROR = 'SKIP_FILE_3'; -- Skips the file if 3 or more errors occur
    ON_ERROR = 'SKIP_FILE_10%';

-- Skips the file if 10% or more rows have errors
TRUNCATE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_ERROR_EX;

SELECT
    s.$1,
    s.$2,
    s.$3,
    s.$4,
    s.$5,
    s.$6
FROM
    @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_ERROR_EX s;

-- File format object
CREATE
OR REPLACE SCHEMA MANAGE_DB.FILE_FORMATS;

CREATE
OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.CSV_FORMAT;

DESC FILE FORMAT MANAGE_DB.FILE_FORMATS.CSV_FORMAT;

-- Altering the type of file format is not possible
ALTER FILE FORMAT MANAGE_DB.FILE_FORMATS.CSV_FORMAT
SET
    SKIP_HEADER = 0;

COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_ERROR_EX (
    ORDER_ID,
    AMOUNT,
    PROFIT,
    QUANTITY,
    CATEGORY,
    SUB_CATEGORY
)
FROM
    (
        SELECT
            s.$1,
            s.$2,
            s.$3,
            s.$4,
            s.$5,
            s.$6
        FROM
            @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_ERROR_EX s
    ) 
    FILE_FORMAT = (
        FORMAT_NAME = MANAGE_DB.FILE_FORMATS.CSV_FORMAT 
        SKIP_HEADER = 1
    ) 
    FILES = (
        'OrderDetails_error.csv',
        'OrderDetails_error2.csv'
    ) 
    ON_ERROR = 'SKIP_FILE_3';

CREATE
OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.JSON_FORMAT TYPE = JSON TIME_FORMAT = AUTO;

DESC FILE FORMAT MANAGE_DB.FILE_FORMATS.JSON_FORMAT;

-- Assignment
SELECT
    *
FROM
    EXERCISE_DB.PUBLIC.CUSTOMERS;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.ASSIGNMENT_STAGE
URL = 's3://snowflake-assignments-mc/fileformat/';

LIST @MANAGE_DB.EXTERNAL_STAGES.ASSIGNMENT_STAGE;

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.ASSIGNMENT_CSV_FORMAT 
TYPE = CSV FIELD_DELIMITER = '|' SKIP_HEADER = 1;

DESC FILE FORMAT MANAGE_DB.FILE_FORMATS.ASSIGNMENT_CSV_FORMAT;

COPY INTO EXERCISE_DB.PUBLIC.CUSTOMERS
FROM @MANAGE_DB.EXTERNAL_STAGES.ASSIGNMENT_STAGE 
FILE_FORMAT = (
    FORMAT_NAME = MANAGE_DB.FILE_FORMATS.ASSIGNMENT_CSV_FORMAT
) 
PATTERN = '.*[.]csv' 
ON_ERROR = 'CONTINUE';

COPY INTO EXERCISE_DB.PUBLIC.CUSTOMERS
FROM @MANAGE_DB.EXTERNAL_STAGES.ASSIGNMENT_STAGE 
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.ASSIGNMENT_CSV_FORMAT 
PATTERN = '.*[.]csv' 
ON_ERROR = 'CONTINUE';

COPY INTO EXERCISE_DB.PUBLIC.CUSTOMERS
FROM @MANAGE_DB.EXTERNAL_STAGES.ASSIGNMENT_STAGE 
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.ASSIGNMENT_CSV_FORMAT 
PATTERN = '.*[.]csv' VALIDATION_MODE = 'RETURN_2_ROWS';

-- VALIDATION_MODE = 'RETURN_ERRORS';
-- Assignment
USE DATABASE EXERCISE_DB;

CREATE OR REPLACE TABLE EMPLOYEES (
    CUSTOMER_ID INT,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(50),
    AGE INT,
    DEPARTMENT VARCHAR(50)
);

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.COPY_STAGE
URL = 's3://snowflake-assignments-mc/copyoptions/example1/';

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.COPY_STAGE_2
URL = 's3://snowflake-assignments-mc/copyoptions/example2';

LIST @MANAGE_DB.EXTERNAL_STAGES.COPY_STAGE;

DESC STAGE MANAGE_DB.EXTERNAL_STAGES.COPY_STAGE;

LIST @MANAGE_DB.EXTERNAL_STAGES.COPY_STAGE_2;

DESC STAGE MANAGE_DB.EXTERNAL_STAGES.COPY_STAGE_2;

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.COPY_CSV_FORMAT 
TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1;

COPY INTO EMPLOYEES
FROM @MANAGE_DB.EXTERNAL_STAGES.COPY_STAGE_2 
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.COPY_CSV_FORMAT
-- VALIDATION_MODE = RETURN_5_ROWS;
-- VALIDATION_MODE = RETURN_ALL_ERRORS;
TRUNCATECOLUMNS = TRUE;

COPY INTO EMPLOYEES
FROM @MANAGE_DB.EXTERNAL_STAGES.COPY_STAGE 
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.COPY_CSV_FORMAT 
FILES = ('employees.csv') 
ON_ERROR = CONTINUE;

SELECT
    *
FROM
    EMPLOYEES;

TRUNCATE TABLE EMPLOYEES;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.JSON_STAGE
URL = 's3://bucketsnowflake-jsondemo';

LIST @MANAGE_DB.EXTERNAL_STAGES.JSON_STAGE;

DESC STAGE MANAGE_DB.EXTERNAL_STAGES.JSON_STAGE;

SELECT
    $1,
    $1:city::string as city,
    METADATA$FILENAME as file_name
    -- *
FROM
    @MANAGE_DB.EXTERNAL_STAGES.JSON_STAGE(
        FILE_FORMAT => MANAGE_DB.FILE_FORMATS.JSON_FORMAT
    )
LIMIT 5;

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.JSON_FORMAT
TYPE = JSON;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.JSON_RAW (raw_file VARIANT);

COPY INTO OUR_FIRST_DB.PUBLIC.JSON_RAW
FROM
    @MANAGE_DB.EXTERNAL_STAGES.JSON_STAGE FILE_FORMAT = MANAGE_DB.FILE_FORMATS.JSON_FORMAT FILES = ('HR_data.json');

-- VALIDATION_MODE = RETURN_5_ROWS;
SELECT
    *
FROM
    OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT
    raw_file:city as city
FROM
    OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT
    $1:city::string as city
FROM
    OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT
    $1:id::int as id
FROM
    OUR_FIRST_DB.PUBLIC.JSON_RAW;

TRUNCATE TABLE OUR_FIRST_DB.PUBLIC.JSON_RAW;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.JSON_STAGE_2
URL = 's3://snowflake-assignments-mc/unstructureddata/';

LIST @MANAGE_DB.EXTERNAL_STAGES.JSON_STAGE_2;

DESC STAGE MANAGE_DB.EXTERNAL_STAGES.JSON_STAGE_2;

SELECT
    -- *
    $1:id::int as id,
    $1:first_name::string as first_name,
    $1:last_name::string as last_name,
    $1:age::int as age
FROM
    @MANAGE_DB.EXTERNAL_STAGES.JSON_STAGE_2 (
        FILE_FORMAT => MANAGE_DB.FILE_FORMATS.JSON_FORMAT
    );

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.JSON_RAW_2 (raw VARIANT);

COPY INTO OUR_FIRST_DB.PUBLIC.JSON_RAW_2
FROM @MANAGE_DB.EXTERNAL_STAGES.JSON_STAGE_2 
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.JSON_FORMAT;

-- VALIDATION_MODE = RETURN_5_ROWS;
SELECT
    *
FROM
    OUR_FIRST_DB.PUBLIC.JSON_RAW_2;

TRUNCATE TABLE OUR_FIRST_DB.PUBLIC.JSON_RAW_2;

SELECT
    $1:id::int as id,
    $1:first_name::string as first_name,
    $1:last_name::string as last_name,
    $1:gender::string as gender,
    $1:city::string as city,
    $1:job:title::string as job_title,
    $1:job.salary::string as salary,
    array_size($1:spoken_languages) as language_count,
    $1:spoken_languages::array as spoken_languages
FROM
    OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT
    RAW_FILE:first_name::string as first_name,
    RAW_FILE:last_name::string as last_name,
    s.value:language::string as language,
    s.value:level::string as level
FROM
    OUR_FIRST_DB.PUBLIC.JSON_RAW,
    TABLE (FLATTEN(RAW_FILE:spoken_languages)) s;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.JSON_PARSED (
    first_name STRING,
    last_name STRING,
    skill_1 STRING,
    skill_2 STRING
);

INSERT INTO
    OUR_FIRST_DB.PUBLIC.JSON_PARSED
SELECT
    $1:first_name::string as first_name,
    $1:last_name::string as last_name,
    $1:Skills[0]::string as skill_1,
    $1:Skills[1]::string as skill_2,
FROM
    OUR_FIRST_DB.PUBLIC.JSON_RAW_2;

SELECT
    *
FROM
    OUR_FIRST_DB.PUBLIC.JSON_PARSED
WHERE
    FIRST_NAME = 'Florina';