-- Create file format and stage object
CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT
TYPE = PARQUET;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
URL = 's3://snowflakeparquetdemo'
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT;

-- Preview the data
LIST @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE;

DESC STAGE MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE;

SELECT *
FROM @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
LIMIT 5;

-- File format in Queries
CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
URL = 's3://snowflakeparquetdemo';

SELECT *
FROM @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE (
    FILE_FORMAT => 'MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT'
)
LIMIT 5;

-- Quotes can be omitted in case of the current namespace
USE MANAGE_DB.FILE_FORMATS;

SELECT *
FROM @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE (
    FILE_FORMAT => MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT
)
LIMIT 5;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
URL = 's3://snowflakeparquetdemo'
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT;

-- Syntax for Querying unstructured data
SELECT
    $1:__index_level_0__,
    $1:cat_id,
    $1:date,
    $1:"dept_id",
    $1:"id",
    $1:"item_id",
    $1:"state_id",
    $1:"store_id",
    $1:"value"
FROM @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
LIMIT 5;

-- Date conversion
SELECT DATE(1);

SELECT DATE(365 * 60 * 60 * 24);

-- Querying with conversions and aliases
SELECT
    $1:__index_level_0__::INT        AS index_level,
    $1:cat_id::VARCHAR(50)           AS category,
    DATE($1:date::INT)               AS date,
    $1:"dept_id"::VARCHAR(50)       AS dept_id,
    $1:"id"::VARCHAR(50)            AS id,
    $1:"item_id"::VARCHAR(50)       AS item_id,
    $1:"state_id"::VARCHAR(50)      AS state_id,
    $1:"store_id"::VARCHAR(50)      AS store_id,
    $1:"value"::INT                 AS value,
    METADATA$FILENAME                AS file_name,
    METADATA$FILE_LAST_MODIFIED      AS last_modified
FROM @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
LIMIT 5;

SELECT
    CURRENT_DATE()                              AS loaded_at,
    CURRENT_TIMESTAMP()                         AS loaded_at_timestamp,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP())       AS loaded_at_timestamp_ntz,
    CURRENT_TIME()                              AS loaded_at_time,
    CURRENT_USER()                              AS loaded_by;

SELECT
    $1,
    $2
FROM @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
LIMIT 5;

CREATE SCHEMA IF NOT EXISTS MANAGE_DB.STORAGE_INTEGRATIONS;

CREATE OR REPLACE STORAGE INTEGRATION S3_INT
		TYPE = EXTERNAL_STAGE
		STORAGE_PROVIDER = S3
		ENABLED = TRUE
		STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::540701075100:role/snowflake-access-role'
		STORAGE_ALLOWED_LOCATIONS = ('s3://amzn-s3-snowflake-tutorial/')
		COMMENT = 'Integration with S3 bucket amzn-s3-snowflake-tutorial';

DESC INTEGRATION S3_INT;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.MOVIE_TITLES (
    SHOW_ID STRING,
    TYPE STRING,
    TITLE STRING,
	DIRECTOR STRING,
	CAST STRING,
	COUNTRY STRING,
	DATE_ADDED STRING,
	RELEASE_YEAR INT,
	RATING STRING,
	DURATION STRING,
	LISTED_IN STRING,
	DESCRIPTION STRING
);

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.MOVIES_CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null')
EMPTY_FIELD_AS_NULL = TRUE
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

DESC FILE FORMAT MANAGE_DB.FILE_FORMATS.MOVIES_CSV_FORMAT;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.MOVIES_STAGE
URL = 's3://amzn-s3-snowflake-tutorial/csv/'
STORAGE_INTEGRATION = S3_INT
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.MOVIES_CSV_FORMAT;

LIST @MANAGE_DB.EXTERNAL_STAGES.MOVIES_STAGE;

SELECT
    $7 AS release_date,
    DATE_FROM_PARTS(
        RIGHT($7, 4),
		CASE SPLIT_PART($7, ' ', 1)
			WHEN 'January' THEN 1
			WHEN 'February' THEN 2
			WHEN 'March' THEN 3
			WHEN 'April' THEN 4
			WHEN 'May' THEN 5
			WHEN 'June' THEN 6
			WHEN 'July' THEN 7
			WHEN 'August' THEN 8
			WHEN 'September' THEN 9
			WHEN 'October' THEN 10
			WHEN 'November' THEN 11
			WHEN 'December' THEN 12
		END,
		SPLIT_PART(SPLIT_PART($7, ',', 1), ' ', 2)
    ) AS release_date
FROM @MANAGE_DB.EXTERNAL_STAGES.MOVIES_STAGE
LIMIT 5;

COPY INTO OUR_FIRST_DB.PUBLIC.MOVIE_TITLES
FROM @MANAGE_DB.EXTERNAL_STAGES.MOVIES_STAGE;
-- VALIDATION_MODE = RETURN_10_ROWS;

SELECT *
FROM OUR_FIRST_DB.PUBLIC.MOVIE_TITLES
LIMIT 10;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.MUSICAL_INSTRUMENTS_STAGE
URL = 's3://amzn-s3-snowflake-tutorial/json/'
STORAGE_INTEGRATION = S3_INT
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.JSON_FORMAT;

LIST @MANAGE_DB.EXTERNAL_STAGES.MUSICAL_INSTRUMENTS_STAGE;

DESC STAGE MANAGE_DB.EXTERNAL_STAGES.MUSICAL_INSTRUMENTS_STAGE;

SELECT
    DATE($1:unixReviewTime::INT) AS review_time,
	DATE_FROM_PARTS(
		RIGHT($1:reviewTime::STRING, 4),
		LEFT($1:reviewTime::STRING, 2),
		SPLIT_PART(SPLIT_PART($1:reviewTime::STRING, ' ', 2), ',', 1)
    ) AS review_time,
	DATE_FROM_PARTS(
		RIGHT($1:reviewTime::STRING, 4),
		LEFT($1:reviewTime::STRING, 2),
		SPLIT(SPLIT($1:reviewTime::STRING, ' ') [1], ',') [0]
    ) AS review_time
FROM @MANAGE_DB.EXTERNAL_STAGES.MUSICAL_INSTRUMENTS_STAGE
LIMIT 5;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.EMPLOYEES (
    ID INT,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    LOCATION STRING,
	DEPARTMENT STRING
);

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.EMPLOYEES_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = '|'
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null')
EMPTY_FIELD_AS_NULL = TRUE;

DESC FILE FORMAT MANAGE_DB.FILE_FORMATS.EMPLOYEES_CSV_FORMAT;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.EMPLOYEES_STAGE
URL = 's3://amzn-s3-snowflake-tutorial/csv/snowpipe'
STORAGE_INTEGRATION = S3_INT
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.EMPLOYEES_CSV_FORMAT;

LIST @MANAGE_DB.EXTERNAL_STAGES.EMPLOYEES_STAGE;

SELECT *
FROM OUR_FIRST_DB.PUBLIC.EMPLOYEES;

CREATE OR REPLACE SCHEMA OUR_FIRST_DB.PIPES;

CREATE OR REPLACE PIPE OUR_FIRST_DB.PIPES.EMPLOYEES_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO OUR_FIRST_DB.PUBLIC.EMPLOYEES
FROM @MANAGE_DB.EXTERNAL_STAGES.EMPLOYEES_STAGE;

COPY INTO OUR_FIRST_DB.PUBLIC.EMPLOYEES
FROM @MANAGE_DB.EXTERNAL_STAGES.EMPLOYEES_STAGE;

DESC PIPE OUR_FIRST_DB.PIPES.EMPLOYEES_PIPE;

TRUNCATE TABLE OUR_FIRST_DB.PUBLIC.EMPLOYEES;

-- To check all the files that have been sent to the pipe
ALTER PIPE OUR_FIRST_DB.PIPES.EMPLOYEES_PIPE REFRESH;

-- To check the status of the pipe if it's running or not
-- To check the no. of pending files
SELECT SYSTEM$PIPE_STATUS('OUR_FIRST_DB.PIPES.EMPLOYEES_PIPE');

-- To check the snowpipe error message
SELECT
	*
FROM
	TABLE (
		VALIDATE_PIPE_LOAD(
			PIPE_NAME => 'OUR_FIRST_DB.PIPES.EMPLOYEES_PIPE',
			START_TIME => DATEADD(HOUR, -1, CURRENT_TIMESTAMP())
		)
	);

-- To check the copy history
SELECT
	*
FROM
	TABLE (
		INFORMATION_SCHEMA.COPY_HISTORY (
			TABLE_NAME => 'OUR_FIRST_DB.PUBLIC.EMPLOYEES',
			START_TIME => DATEADD(HOUR, -1, CURRENT_TIMESTAMP())
		)
	);

SHOW PIPES;

SHOW DATABASES;
SHOW DATABASES LIKE '%BEETLE%';

SHOW SCHEMAS;
SHOW SCHEMAS LIKE '%VEG%';
SHOW SCHEMAS LIKE '%VEG%' IN DATABASE BEETLE03_DB;


DESCRIBE PIPE OUR_FIRST_DB.PIPES.EMPLOYEES_PIPE;

-- To pause the pipe
ALTER PIPE OUR_FIRST_DB.PIPES.EMPLOYEES_PIPE SET PIPE_EXECUTION_PAUSED = TRUE;

-- Use of cortex PARSE_DOCUMENT and CLASSIFY_TEXT function
WITH content AS (
    SELECT
        SPLIT_PART(RELATIVE_PATH, '/', -1) AS file_name,
        SNOWFLAKE.CORTEX.PARSE_DOCUMENT (
            @COMMON_DB.RESOURCES.COURSE_FILES,
            RELATIVE_PATH,
            { 'mode': 'OCR' }
        ):content::STRING AS content
    FROM
        DIRECTORY(@COMMON_DB.RESOURCES.COURSE_FILES)
    WHERE
        CONTAINS(RELATIVE_PATH, 'garden_kb/')
)
SELECT
    file_name,
    content,
    SNOWFLAKE.CORTEX.CLASSIFY_TEXT(
        content,
        (
            SELECT
                ARRAY_AGG(DISTINCT PLANT_NAME)
            FROM
                VEGETABLE_DETAILS
        )
    ) AS classified
FROM content;

SELECT
    SPLIT_PART(RELATIVE_PATH, '/', -1) AS file_name,
    SNOWFLAKE.CORTEX.PARSE_DOCUMENT (
        @COMMON_DB.RESOURCES.COURSE_FILES,
        RELATIVE_PATH,
        { 'mode': 'OCR' }
    ):content::STRING AS content,
    SNOWFLAKE.CORTEX.CLASSIFY_TEXT(
        content,
        (
            SELECT
                ARRAY_AGG(DISTINCT PLANT_NAME)
            FROM
                VEGETABLE_DETAILS
        )
    ):label::STRING AS classified
FROM DIRECTORY(@COMMON_DB.RESOURCES.COURSE_FILES)
WHERE CONTAINS(RELATIVE_PATH, 'garden_kb/');

-- Time travel
SELECT *
FROM OUR_FIRST_DB.PUBLIC.EMPLOYEES
AT (TIMESTAMP => '2025-10-14 10:00:00'::TIMESTAMP_TZ);

SELECT *
FROM OUR_FIRST_DB.PUBLIC.EMPLOYEES
AT (OFFSET => -120);

-- 2 minutes ago
SELECT *
FROM OUR_FIRST_DB.PUBLIC.EMPLOYEES
BEFORE (STATEMENT => '019856d5-0000-0000-0000-000000000000');

-- Assignment
CREATE OR REPLACE TABLE LEARNING_DB.PUBLIC.PART
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;

SELECT * FROM LEARNING_DB.PUBLIC.PART
ORDER BY P_MFGR DESC;

UPDATE LEARNING_DB.PUBLIC.PART
SET P_MFGR='Manufacturer#CompanyX'
WHERE P_MFGR='Manufacturer#5';

SELECT * FROM LEARNING_DB.PUBLIC.PART
WHERE P_MFGR='Manufacturer#CompanyX'
LIMIT 10;

SELECT * FROM LEARNING_DB.PUBLIC.PART
AT (OFFSET => -60 * 2);

SELECT * FROM LEARNING_DB.PUBLIC.PART
BEFORE (STATEMENT => '01c53ca3-0309-89ee-002e-f967007f53b2');

-- Second assignment
CREATE DATABASE TIMETRAVEL_EXERCISE;

CREATE SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;

CREATE TABLE CUSTOMER AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
LIMIT 500;

DROP SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;

SELECT * FROM TIMETRAVEL_EXERCISE.COMPANY_X.CUSTOMER;

UNDROP SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;

-- Zero copy cloning assignment

CREATE OR REPLACE TABLE LEARNING_DB.PUBLIC.SUPPLIER
AS
SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."SUPPLIER";

CREATE OR REPLACE TABLE LEARNING_DB.PUBLIC.SUPPLIER_CLONE
CLONE LEARNING_DB.PUBLIC.SUPPLIER;

SELECT * FROM LEARNING_DB.PUBLIC.SUPPLIER_CLONE LIMIT 100;

UPDATE LEARNING_DB.PUBLIC.SUPPLIER_CLONE
SET S_PHONE = '00-000-000-0000';

SELECT * FROM LEARNING_DB.PUBLIC.SUPPLIER_CLONE BEFORE (STATEMENT => '01c541cc-0309-8bc7-002e-f9670086dabe');

CREATE OR REPLACE TABLE LEARNING_DB.PUBLIC.SUPPLIER_CLONE_2
CLONE LEARNING_DB.PUBLIC.SUPPLIER
BEFORE (STATEMENT => '01c541cc-0309-8bc7-002e-f9670086dabe');

SELECT * FROM LEARNING_DB.PUBLIC.SUPPLIER_CLONE_2 LIMIT 100;

DROP TABLE LEARNING_DB.PUBLIC.SUPPLIER_CLONE;

UNDROP TABLE LEARNING_DB.PUBLIC.SUPPLIER_CLONE;

-- Sampling assignment
CREATE
OR REPLACE TRANSIENT TABLE LEARNING_DB.PUBLIC.CUSTOMER_ADDRESS_SAMPLE_5 AS
SELECT
    *
FROM
    SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER_ADDRESS SAMPLE ROW (5) SEED (2);

SELECT * FROM LEARNING_DB.PUBLIC.CUSTOMER_ADDRESS_SAMPLE_5;

CREATE
OR REPLACE TRANSIENT TABLE LEARNING_DB.PUBLIC.CUSTOMER_SAMPLE_1 AS
SELECT
    *
FROM
    SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER SAMPLE SYSTEM (1) SEED (2);

SELECT COUNT(*) FROM LEARNING_DB.PUBLIC.CUSTOMER_SAMPLE_1;

-- Task
CREATE OR REPLACE TRANSIENT TABLE LEARNING_DB.PUBLIC.CUSTOMERS (
    CUSTOMER_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CUSTOMER_NAME STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE LEARNING_DB.PUBLIC.CUSTOMER_TASK_LOG (
    TASK_NAME STRING,
    RUN_TIME TIMESTAMP_LTZ,
    ROW_COUNT NUMBER
);

CREATE OR REPLACE TASK TASK_1
WAREHOUSE = BEETLE03_WH
SCHEDULE = '1 MINUTE'
AS
INSERT INTO LEARNING_DB.PUBLIC.CUSTOMERS (CUSTOMER_NAME)
VALUES ('John Doe');

CREATE OR REPLACE TASK TASK_2
WAREHOUSE = BEETLE03_WH
AFTER TASK_1
WHEN SYSTEM$GET_PREDECESSOR_RETURN_VALUE('TASK_1') > 0
AS
INSERT INTO LEARNING_DB.PUBLIC.CUSTOMER_TASK_LOG (TASK_NAME, RUN_TIME, ROW_COUNT)
SELECT 'TASK_2', CURRENT_TIMESTAMP(), COUNT(*)
FROM LEARNING_DB.PUBLIC.CUSTOMERS;

SHOW TASKS;

ALTER TASK TASK_1 RESUME;
ALTER TASK TASK_1 SUSPEND;

-- Recursively resume a specified task and all it's dependent tasks.
SELECT SYSTEM$TASK_DEPENDENTS_ENABLE('TASK_1');

-- Using CRON
-- General syntax of schedule
-- SCHEDULE = 'USING CRON * * * * * TIMEZONE';

-- * * * * * *
-- | | | | | |
-- | | | | | +----- Day of the Week (0-7, where 0 and 7 are Sunday)
-- | | | | +------- Month (1-12)
-- | | | +--------- Day of the Month (1-31)
-- | +----------- Hour (0-23)
-- +------------- Minute (0-59)

CREATE OR REPLACE PROCEDURE CREATE_CUSTOMER_SQL(CUSTOMER_NAME STRING DEFAULT 'Default Customer')
RETURNS VARCHAR NOT NULL
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO LEARNING_DB.PUBLIC.CUSTOMERS (CUSTOMER_NAME)
    VALUES (:CUSTOMER_NAME);
    RETURN 'Customer "' || :CUSTOMER_NAME || '" created successfully';
END;
$$;

CREATE OR REPLACE PROCEDURE CREATE_CUSTOMER_JS(CUSTOMER_NAME STRING)
RETURNS VARCHAR NOT NULL
LANGUAGE JAVASCRIPT
AS
$$
    const sql = "INSERT INTO LEARNING_DB.PUBLIC.CUSTOMERS (CUSTOMER_NAME) VALUES (:1)";
    snowflake.execute({ sqlText: sql, binds: [CUSTOMER_NAME] });
    return 'Customer "' + CUSTOMER_NAME + '" created successfully';
$$;

CREATE OR REPLACE PROCEDURE EXECUTE_TASKS()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL
AS
$$
BEGIN
    CALL CREATE_CUSTOMER_SQL('Jane Doe');
    CALL CREATE_CUSTOMER_JS('John Smith');
    RETURN 'Tasks executed successfully';
END;
$$;

CREATE OR REPLACE TASK EXECUTE_TASKS_TASK
WAREHOUSE = BEETLE03_WH
SCHEDULE = '1 MINUTE'
AS
CALL EXECUTE_TASKS();

SHOW PROCEDURES LIKE 'CREATE_CUSTOMER%';

CALL CREATE_CUSTOMER_SQL(CUSTOMER_NAME => 'George Weasley');
CALL CREATE_CUSTOMER_SQL();
CALL CREATE_CUSTOMER_JS(CUSTOMER_NAME => 'Draco Malfoy');

SELECT * FROM LEARNING_DB.PUBLIC.CUSTOMERS;

SELECT
    *
FROM
    TABLE (
        INFORMATION_SCHEMA.TASK_HISTORY (TASK_NAME => 'EXECUTE_TASKS_TASK')
    )
ORDER BY
    SCHEDULED_TIME DESC;

-- Streams
CREATE OR REPLACE TRANSIENT TABLE LEARNING_DB.PUBLIC.PRODUCTS (
    PRODUCT_ID NUMBER AUTOINCREMENT (1, 1),
    PRODUCT_NAME STRING,
    PRODUCT_PRICE NUMBER,
    STORE_ID NUMBER
);

SELECT * FROM LEARNING_DB.PUBLIC.PRODUCTS;

CREATE OR REPLACE TRANSIENT TABLE LEARNING_DB.PUBLIC.STORES (
    STORE_ID NUMBER AUTOINCREMENT (1, 1),
    STORE_NAME STRING,
    LOCATION STRING
);

SELECT * FROM LEARNING_DB.PUBLIC.STORES;

CREATE OR REPLACE TRANSIENT TABLE LEARNING_DB.PUBLIC.PRODUCTS_FINAL (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME STRING,
    PRODUCT_PRICE NUMBER,
    STORE_ID NUMBER,
    STORE_NAME STRING,
    LOCATION STRING
);

SELECT * FROM LEARNING_DB.PUBLIC.PRODUCTS_FINAL;

INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_PRICE, STORE_ID)
VALUES 
    ('Laptop', 1000, 1),
    ('Mouse', 50, 1),
    ('Keyboard', 100, 2),
    ('Monitor', 500, 2),
    ('Headphones', 200, 3);

INSERT INTO STORES (STORE_NAME, LOCATION)
VALUES 
    ('Store 1', 'Location 1'),
    ('Store 2', 'Location 2'),
    ('Store 3', 'Location 3'),
    ('Store 4', 'Location 4'),
    ('Store 5', 'Location 5');

INSERT INTO PRODUCTS_FINAL (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, STORE_ID, STORE_NAME, LOCATION)
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRODUCT_PRICE,
    P.STORE_ID,
    S.STORE_NAME,
    S.LOCATION
FROM LEARNING_DB.PUBLIC.PRODUCTS P
JOIN LEARNING_DB.PUBLIC.STORES S ON P.STORE_ID = S.STORE_ID;

CREATE OR REPLACE STREAM LEARNING_DB.PUBLIC.PRODUCTS_STREAM
ON TABLE LEARNING_DB.PUBLIC.PRODUCTS;

SHOW STREAMS;

DESC STREAM LEARNING_DB.PUBLIC.PRODUCTS_STREAM;

SELECT * FROM LEARNING_DB.PUBLIC.PRODUCTS_STREAM;

INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_PRICE, STORE_ID)
VALUES 
    ('Charger', 20, 1),
    ('Cable', 15, 2);

INSERT INTO PRODUCTS_FINAL (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, STORE_ID, STORE_NAME, LOCATION)
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRODUCT_PRICE,
    P.STORE_ID,
    S.STORE_NAME,
    S.LOCATION
FROM LEARNING_DB.PUBLIC.PRODUCTS_STREAM P
JOIN LEARNING_DB.PUBLIC.STORES S ON P.STORE_ID = S.STORE_ID;

MERGE INTO
    LEARNING_DB.PUBLIC.PRODUCTS_FINAL PF USING (
        SELECT
            PS.PRODUCT_ID,
            PS.PRODUCT_NAME,
            PS.PRODUCT_PRICE,
            PS.STORE_ID,
            S.STORE_NAME,
            S.LOCATION,
            PS.METADATA$ACTION,
            PS.METADATA$ISUPDATE
        FROM
            LEARNING_DB.PUBLIC.PRODUCTS_STREAM PS
            JOIN LEARNING_DB.PUBLIC.STORES S ON PS.STORE_ID = S.STORE_ID
    ) FPS ON PF.PRODUCT_ID = FPS.PRODUCT_ID
WHEN MATCHED AND
    FPS.METADATA$ACTION = 'INSERT'
    AND FPS.METADATA$ISUPDATE = 'TRUE'
THEN UPDATE SET
    PF.PRODUCT_NAME = FPS.PRODUCT_NAME,
    PF.PRODUCT_PRICE = FPS.PRODUCT_PRICE,
    PF.STORE_ID = FPS.STORE_ID
WHEN MATCHED AND
    FPS.METADATA$ACTION = 'DELETE'
    AND FPS.METADATA$ISUPDATE = 'FALSE'
THEN DELETE
WHEN NOT MATCHED AND
    FPS.METADATA$ACTION = 'INSERT'
    AND FPS.METADATA$ISUPDATE = 'FALSE'
THEN INSERT (
        PRODUCT_ID,
        PRODUCT_NAME,
        PRODUCT_PRICE,
        STORE_ID,
        STORE_NAME,
        LOCATION
    )
    VALUES
        (
            FPS.PRODUCT_ID,
            FPS.PRODUCT_NAME,
            FPS.PRODUCT_PRICE,
            FPS.STORE_ID,
            FPS.STORE_NAME,
            FPS.LOCATION
        );

INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_PRICE, STORE_ID)
VALUES 
    ('USB drive', 150, 5);

DESC TABLE LEARNING_DB.PUBLIC.PRODUCTS;

SHOW PARAMETERS IN TABLE LEARNING_DB.PUBLIC.PRODUCTS;

ALTER TABLE LEARNING_DB.PUBLIC.PRODUCTS SET MAX_DATA_EXTENSION_TIME_IN_DAYS = 2;

UPDATE PRODUCTS SET PRODUCT_PRICE = 4000 WHERE PRODUCT_NAME = 'USB drive';
DELETE FROM PRODUCTS WHERE PRODUCT_NAME = 'Cable';

CREATE OR REPLACE PROCEDURE PROCESS_PRODUCT_CHANGES()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO
        LEARNING_DB.PUBLIC.PRODUCTS_FINAL PF USING (
            SELECT
                PS.PRODUCT_ID,
                PS.PRODUCT_NAME,
                PS.PRODUCT_PRICE,
                PS.STORE_ID,
                S.STORE_NAME,
                S.LOCATION,
                PS.METADATA$ACTION,
                PS.METADATA$ISUPDATE
            FROM
                LEARNING_DB.PUBLIC.PRODUCTS_STREAM PS
                JOIN LEARNING_DB.PUBLIC.STORES S ON PS.STORE_ID = S.STORE_ID
        ) FPS ON PF.PRODUCT_ID = FPS.PRODUCT_ID
    WHEN MATCHED AND
        FPS.METADATA$ACTION = 'INSERT'
        AND FPS.METADATA$ISUPDATE = 'TRUE'
    THEN UPDATE SET
        PF.PRODUCT_NAME = FPS.PRODUCT_NAME,
        PF.PRODUCT_PRICE = FPS.PRODUCT_PRICE,
        PF.STORE_ID = FPS.STORE_ID
    WHEN MATCHED AND
        FPS.METADATA$ACTION = 'DELETE'
        AND FPS.METADATA$ISUPDATE = 'FALSE'
    THEN DELETE
    WHEN NOT MATCHED AND
        FPS.METADATA$ACTION = 'INSERT'
        AND FPS.METADATA$ISUPDATE = 'FALSE'
    THEN INSERT (
            PRODUCT_ID,
            PRODUCT_NAME,
            PRODUCT_PRICE,
            STORE_ID,
            STORE_NAME,
            LOCATION
        )
        VALUES
            (
                FPS.PRODUCT_ID,
                FPS.PRODUCT_NAME,
                FPS.PRODUCT_PRICE,
                FPS.STORE_ID,
                FPS.STORE_NAME,
                FPS.LOCATION
            );

    RETURN 'Merge completed successfully';
END;
$$;

SHOW PROCEDURES;

CREATE OR REPLACE TASK PROCESS_PRODUCT_CHANGES_TASK
WAREHOUSE = BEETLE03_WH
SCHEDULE = '1 MINUTE'
WHEN
    SYSTEM$STREAM_HAS_DATA('PRODUCTS_STREAM')
AS
CALL PROCESS_PRODUCT_CHANGES();

SHOW TASKS;

SELECT SYSTEM$STREAM_HAS_DATA('PRODUCTS_STREAM');

-- Append Only Stream ie. only insert operations are tracked
CREATE
OR REPLACE STREAM PRODUCTS_APPEND_STREAM ON TABLE PRODUCTS APPEND_ONLY = TRUE;

SELECT * FROM LEARNING_DB.PUBLIC.PRODUCTS_APPEND_STREAM;

-- Track table changes
ALTER TABLE LEARNING_DB.PUBLIC.PRODUCTS SET CHANGE_TRACKING = TRUE;

SELECT * FROM LEARNING_DB.PUBLIC.PRODUCTS
CHANGES(INFORMATION => DEFAULT) 
AT (OFFSET => -20*60);

SELECT * FROM LEARNING_DB.PUBLIC.PRODUCTS
CHANGES(INFORMATION => APPEND_ONLY) 
AT (TIMESTAMP => '2025-10-15 10:00:00'::TIMESTAMP_TZ);

-- Materialize view
SELECT 
AVG(PS_SUPPLYCOST) as PS_SUPPLYCOST_AVG,
AVG(PS_AVAILQTY) as PS_AVAILQTY_AVG,
MAX(PS_COMMENT) as PS_COMMENT_MAX
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PARTSUPP;
-- Time Taken 22s

CREATE
OR REPLACE MATERIALIZED VIEW LEARNING_DB.PUBLIC.PARTSUPP AS
SELECT
    AVG(PS_SUPPLYCOST) as PS_SUPPLYCOST_AVG,
    AVG(PS_AVAILQTY) as PS_AVAILQTY_AVG,
    MAX(PS_COMMENT) as PS_COMMENT_MAX
FROM
    SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PARTSUPP;

SELECT * FROM LEARNING_DB.PUBLIC.PARTSUPP;
-- Time taken 524ms

-- Data masking policy
CREATE
OR REPLACE
MASKING POLICY
    PHONE AS (VAL VARCHAR) RETURNS VARCHAR -> CASE
        WHEN CURRENT_ROLE() in (ACCOUNT_ADMIN, SYSADMIN) THEN VAL
        ELSE LEFT(VAL, 2) || "#-###-###"
    END;

DESC MASKING POLICY PHONE;

SHOW MASKING POLICIES;

ALTER TABLE CUSTOMERS MODIFY COLUMN PHONE
SET MASKING POLICY PHONE;

ALTER TABLE CUSTOMERS MODIFY COLUMN PHONE
UNSET MASKING POLICY;

ALTER MASKING POLICY PHONE
SET
    BODY -> CASE
        WHEN CURRENT_ROLE() in (ACCOUNT_ADMIN, SYSADMIN) THEN VAL
        ELSE CONCAT(LEFT(VAL, 2), "#-###-###")
    END;

SELECT * FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME => 'PHONE'));

-- Access management

--      +--ACCOUNTADMIN--+
--      ^                ^
--      |                |
-- SECURITYADMIN      SYSADMIN
--      ^                ^
--      |                |
--  USERADMIN       <CUSTOM_ROLE>
--      ^
--      |
--   PUBLIC

-- Types of Access Control:
-- 1. Discretionary access control (DAC) ie owner decides who can access
-- 2. Role based access control (RBAC) ie role decides who can access

-- Grant privilege on object to role
GRANT <PRIVILEGE>
ON <OBJECT_TYPE> <OBJECT_NAME>
TO ROLE <ROLE>;

-- Grant privilege on object to share
GRANT <PRIVILEGE>
ON <OBJECT_TYPE> <OBJECT_NAME>
TO SHARE <SHARE_NAME>;


-- Grant role to user
GRANT ROLE <ROLE>
TO USER <USER>;

-- Grant role to role
GRANT ROLE <ROLE>
TO ROLE <ROLE>;

CREATE ROLE <ROLE_NAME>;

CREATE USER john PASSWORD = '123'
DEFAULT ROLE ACCOUNTADMIN
MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE ACCOUNTADMIN
TO USER john;
