-- Create file format and stage object
CREATE
OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT TYPE = 'parquet';

CREATE
OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE url = 's3://snowflakeparquetdemo' FILE_FORMAT = MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT;

-- Preview the data
LIST @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE;

DESC STAGE MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE;

SELECT
    *
FROM
    @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
LIMIT 5;

-- File format in Queries
CREATE
OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE url = 's3://snowflakeparquetdemo';

SELECT
    *
FROM
    @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE (
        file_format => 'MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT'
    )
LIMIT 5;

-- Quotes can be omitted in case of the current namespace
USE MANAGE_DB.FILE_FORMATS;

SELECT
    *
FROM
    @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE (
        file_format => MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT
    )
LIMIT 5;

CREATE
OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE url = 's3://snowflakeparquetdemo' FILE_FORMAT = MANAGE_DB.FILE_FORMATS.PARQUET_FORMAT;

-- Syntax for Querying unstructured data
SELECT
    $1:__index_level_0__,
    $1:cat_id,
    $1:date,
    $1:"__index_level_0__",
    $1:"cat_id",
    $1:"d",
    $1:"date",
    $1:"dept_id",
    $1:"id",
    $1:"item_id",
    $1:"state_id",
    $1:"store_id",
    $1:"value"
FROM
    @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
LIMIT 5;

-- Date conversion
SELECT
    DATE(1);

SELECT
    DATE(365 * 60 * 60 * 24);

-- Querying with conversions and aliases
SELECT
    $1:__index_level_0__::int as index_level,
    $1:cat_id::VARCHAR(50) as category,
    DATE($1:date::int) as Date,
    $1:"dept_id"::VARCHAR(50) as Dept_ID,
    $1:"id"::VARCHAR(50) as ID,
    $1:"item_id"::VARCHAR(50) as Item_ID,
    $1:"state_id"::VARCHAR(50) as State_ID,
    $1:"store_id"::VARCHAR(50) as Store_ID,
    $1:"value"::int as value,
    METADATA$FILENAME as file_name,
    METADATA$file_last_modified as last_modified
FROM
    @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
LIMIT 5;

SELECT
    CURRENT_DATE() as loaded_at,
    CURRENT_TIMESTAMP() as loaded_at_timestamp,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) as loaded_at_timestamp_ntz,
    CURRENT_TIME() as loaded_at_time,
    CURRENT_USER() as loaded_by;

SELECT
    $1,
    $2,
FROM
    @MANAGE_DB.EXTERNAL_STAGES.PARQUET_STAGE
LIMIT 5;

CREATE SCHEMA IF NOT EXISTS MANAGE_DB.STORAGE_INTEGRATIONS;

CREATE OR REPLACE STORAGE INTEGRATION S3_INT
		TYPE = EXTERNAL_STAGE
		STORAGE_PROVIDER = S3
		ENABLED = TRUE
		STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::540701075100:role/snowflake-access-role'
		STORAGE_ALLOWED_LOCATIONS = ('s3://amzn-s3-snowflake-tutorial/')
		COMMENT = 'Integration with S3 bucket amzn-s3-snowflake-tutorial';

DESC INTEGRATION S3_INT;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.MOVIE_TITLES (
    SHOW_ID STRING,
    TYPE STRING,
    TITLE STRING,
	DIRECTOR STRING,
	CAST STRING,
	COUNTRY STRING,
	DATE_ADDED STRING,
	RELEASE_YEAR INT,
	RATING STRING,
	DURATION STRING,
	LISTED_IN STRING,
	DESCRIPTION STRING
);

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.MOVIES_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null')
EMPTY_FIELD_AS_NULL = TRUE
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

DESC FILE FORMAT MANAGE_DB.FILE_FORMATS.MOVIES_CSV_FORMAT;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.MOVIES_STAGE
    URL = 's3://amzn-s3-snowflake-tutorial/csv/'
    STORAGE_INTEGRATION = S3_INT
    FILE_FORMAT = MANAGE_DB.FILE_FORMATS.MOVIES_CSV_FORMAT;

LIST @MANAGE_DB.EXTERNAL_STAGES.MOVIES_STAGE;

SELECT
	$7 as release_date,
	DATE_FROM_PARTS(
		RIGHT($7, 4),
		CASE SPLIT_PART($7, ' ', 1)
			WHEN 'January' THEN 1
			WHEN 'February' THEN 2
			WHEN 'March' THEN 3
			WHEN 'April' THEN 4
			WHEN 'May' THEN 5
			WHEN 'June' THEN 6
			WHEN 'July' THEN 7
			WHEN 'August' THEN 8
			WHEN 'September' THEN 9
			WHEN 'October' THEN 10
			WHEN 'November' THEN 11
			WHEN 'December' THEN 12
		END,
		SPLIT_PART(SPLIT_PART($7, ',', 1), ' ', 2)
	) as release_date
FROM
	@MANAGE_DB.EXTERNAL_STAGES.MOVIES_STAGE
LIMIT
	5;

COPY INTO OUR_FIRST_DB.PUBLIC.MOVIE_TITLES
FROM @MANAGE_DB.EXTERNAL_STAGES.MOVIES_STAGE;
-- VALIDATION_MODE = RETURN_10_ROWS;

SELECT * FROM OUR_FIRST_DB.PUBLIC.MOVIE_TITLES LIMIT 10;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.MUSICAL_INSTRUMENTS_STAGE
    URL = 's3://amzn-s3-snowflake-tutorial/json/'
    STORAGE_INTEGRATION = S3_INT
    FILE_FORMAT = MANAGE_DB.FILE_FORMATS.JSON_FORMAT;

LIST @MANAGE_DB.EXTERNAL_STAGES.MUSICAL_INSTRUMENTS_STAGE;

DESC STAGE MANAGE_DB.EXTERNAL_STAGES.MUSICAL_INSTRUMENTS_STAGE;

SELECT
	DATE($1:unixReviewTime::INT) as review_time,
	DATE_FROM_PARTS(
		RIGHT($1:reviewTime::STRING, 4),
		LEFT($1:reviewTime::STRING, 2),
		SPLIT_PART(SPLIT_PART($1:reviewTime::STRING, ' ', 2), ',', 1)
	) as review_time,
	DATE_FROM_PARTS(
		RIGHT($1:reviewTime::STRING, 4),
		LEFT($1:reviewTime::STRING, 2),
		SPLIT(SPLIT($1:reviewTime::STRING, ' ') [1], ',') [0]
	) as review_time,
FROM
	@MANAGE_DB.EXTERNAL_STAGES.MUSICAL_INSTRUMENTS_STAGE
LIMIT
	5;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.EMPLOYEES (
    ID INT,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    LOCATION STRING,
	DEPARTMENT STRING
);

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.EMPLOYEES_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = '|'
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null')
EMPTY_FIELD_AS_NULL = TRUE;

DESC FILE FORMAT MANAGE_DB.FILE_FORMATS.EMPLOYEES_CSV_FORMAT;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.EMPLOYEES_STAGE
    URL = 's3://amzn-s3-snowflake-tutorial/csv/snowpipe'
    STORAGE_INTEGRATION = S3_INT
    FILE_FORMAT = MANAGE_DB.FILE_FORMATS.EMPLOYEES_CSV_FORMAT;

LIST @MANAGE_DB.EXTERNAL_STAGES.EMPLOYEES_STAGE;

SELECT * FROM OUR_FIRST_DB.PUBLIC.EMPLOYEES;

CREATE OR REPLACE SCHEMA OUR_FIRST_DB.PIPES;

CREATE OR REPLACE PIPE OUR_FIRST_DB.PIPES.EMPLOYEES_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO OUR_FIRST_DB.PUBLIC.EMPLOYEES
FROM @MANAGE_DB.EXTERNAL_STAGES.EMPLOYEES_STAGE;

COPY INTO OUR_FIRST_DB.PUBLIC.EMPLOYEES
FROM @MANAGE_DB.EXTERNAL_STAGES.EMPLOYEES_STAGE;

DESC PIPE OUR_FIRST_DB.PIPES.EMPLOYEES_PIPE;

TRUNCATE TABLE OUR_FIRST_DB.PUBLIC.EMPLOYEES;

ALTER PIPE OUR_FIRST_DB.PIPES.EMPLOYEES_PIPE REFRESH;

SELECT SYSTEM$PIPE_STATUS('OUR_FIRST_DB.PIPES.EMPLOYEES_PIPE');

SELECT
	*
FROM
	TABLE (
		VALIDATE_PIPE_LOAD(
			PIPE_NAME => 'OUR_FIRST_DB.PIPES.EMPLOYEES_PIPE',
			START_TIME => DATEADD(HOUR, -1, CURRENT_TIMESTAMP())
		)
	);

SELECT
	*
FROM
	TABLE (
		INFORMATION_SCHEMA.COPY_HISTORY (
			TABLE_NAME => 'OUR_FIRST_DB.PUBLIC.EMPLOYEES',
			START_TIME => DATEADD(HOUR, -1, CURRENT_TIMESTAMP())
		)
	);

SHOW PIPES;
